import type { Metadata } from 'next';

import { Sidebar } from '@/components/shared';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const DashboardLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <div className="relative grid min-h-screen grid-cols-12 gap-12">
    <Sidebar className="col-span-2" />
    <section className="col-span-10 px-5 py-6">{children}</section>
  </div>
);

export default DashboardLayout;
